import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
// import { SessionProvider } from "next-auth/react"
import { Providers } from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className="h-full w-full flex flex-col bg-gradient-to-r from-[#5E376C] to-[#675080]">
      <Providers>
        <Navbar />
        {children}
        {/* <Footer /> */}
      </Providers>
    </body>
    </html>
  );
}
